#!/usr/bin/env bash

# Color
GREEN='\033[92m'
RED='\033[91m'
NC='\033[0m'

# Handler logic signed binary
sign_file() {
    BASE_PATH="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"

    local TARGET_FILE=$1
    local MANIFEST="$BASE_PATH/lib/core/database/signed_manifest.json"
    local FILENAME=$(basename "$TARGET_FILE")
    local HASH=$(sha256sum "$TARGET_FILE" | awk '{print $1}')
    local SIZE=$(stat -c%s "$TARGET_FILE")

    echo -e "${RED}DEBUG: $MANIFEST${NC}"
    python3 -c "
import json, os
MANIFEST_PATH = '$MANIFEST'
try:
    with open(MANIFEST_PATH, 'r') as f: data = json.load(f)
except: data = {}

data['$FILENAME'] = {'sha256': '$HASH', 'size_bytes': $SIZE}

with open(MANIFEST_PATH, 'w') as f:
    json.dump(data, f, indent=4)
"
}

#Logic core compiler
compile_modules() {
    local BASE_PATH
    BASE_PATH="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"

    if [ -d "$BASE_PATH" ]; then
        cd "$BASE_PATH" || return 1
    fi
    echo -e "${RED}DEBUG: $BASE_PATH${NC}"
    # --- BAGIAN GOLANG ---
    if command -v go > /dev/null; then
        [ -f "go.mod" ] && rm go.mod

        echo -e "${GREEN}[*] Initializing Go modules.${NC}"
        go mod init github.com/storm-os/Cyber-Pentest

        echo -e "${GREEN}\n[*] Downloading dependencies.${NC}"
        go get github.com/google/gopacket@latest
        go get github.com/google/gopacket/pcap@latest
        go mod tidy

        find modules/ -name "*.go" | while read -r src; do
            output="${src%.go}"
            CGO_ENABLED=1 go build -mod=mod -o "$output" "$src"
            chmod +x "$output"

            sign_file "$output"
        done
    fi

    # --- LOGIKA C ---
    if command -v gcc > /dev/null; then
        find modules/ -name "*.c" | while read -r src; do
            output="${src%.c}"

            if grep -q "pcap.h" "$src"; then
                gcc "$src" -o "$output" -lpcap
            else
                gcc "$src" -o "$output"
            fi
            chmod +x "$output"

            sign_file "$output"
        done
    fi
}

