#!/usr/bin/env sh

# Color
GREEN='\033[92m'
RED='\033[91m'
BLUE='\033[94m'
NC='\033[0m'

#Logic core compiler
compile_modules() {
    local BASE_PATH
    BASE_PATH="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"

    if [ -d "$BASE_PATH" ]; then
        cd "$BASE_PATH" || return 1
    fi

    echo -e "${GREEN}[*] Auto-detected Path: $(pwd)${NC}"

    # --- LOGIKA GOLANG ---
    if command -v go > /dev/null; then
        if [ ! -f "go.mod" ]; then
            go mod init storm-os 2>/dev/null
        fi

        echo -e "${GREEN}[*] Fetching dependencies...${NC}"
        go get github.com/google/gopacket github.com/google/gopacket/pcap 2>/dev/null
        go mod tidy 2>/dev/null

        find modules/ -name "*.go" | while read -r src; do
            output="${src%.go}"
            echo -e "${GREEN}[+] Compiling Go: $src${NC}"
            CGO_ENABLED=1 go build -o "$output" "$src"
        done
    fi

    # --- LOGIKA C ---
    if command -v gcc > /dev/null; then
        find modules/ -name "*.c" | while read -r src; do
            output="${src%.c}"
            echo -e "${GREEN}[+] Compiling C: $src${NC}"
            if grep -q "pcap.h" "$src"; then
                gcc "$src" -o "$output" -lpcap
            else
                gcc "$src" -o "$output"
            fi
        done
    fi
}
