#!/usr/bin/env sh

# Color
GREEN='\033[92m'
RED='\033[91m'
BLUE='\033[94m'
NC='\033[0m'

#Logic core compiler
compile_modules() {
    echo -e "${GREEN}[*] Scanning and Compiling core modules.${NC}"

    # --- BAGIAN GOLANG ---
    if command -v go > /dev/null; then
        if [ ! -f "go.mod" ]; then
            echo -e "${GREEN}[*] Initializing Go modules.${NC}"
            go mod init storm-os 2>/dev/null
        fi

        echo -e "${GREEN}[*] Fetching remote dependencies (gopacket)${NC}"
        go get github.com/google/gopacket > /dev/null 2>&1
        go get github.com/google/gopacket/pcap > /dev/null 2>&1
        go mod tidy > /dev/null 2>&1

        find modules/ -name "*.go" | while read -r src; do
            output="${src%.go}"
            echo -e "${GREEN}[+] Compiling Go: $src${NC}"
            go build -o "$output" "$src" && chmod +x "$output"
        done
    fi

    # --- C ---
    if command -v gcc > /dev/null; then
        find modules/ -name "*.c" | while read -r src; do
            output="${src%.c}"
            echo -e "${GREEN}[+] Compiling C: $src${NC}"

            # Cek apakah file C mengandung pcap (butuh link -lpcap)
            if grep -q "pcap.h" "$src"; then
                gcc "$src" -o "$output" -lpcap && chmod +x "$output"
            else
                gcc "$src" -o "$output" && chmod +x "$output"
            fi
        done
    fi
}
