#!/usr/bin/env python3

# MIT License
# Copyright (c) Storm Framework

# This file is protected by a License. Read the full LICENSE in the root.

# All import
import os
import time
import sys
import readline  # noqa: F401
import app.base.config_ui as ui
import lib.smf.core.sf.ldch as ldch

from app.base.config_update import check_update
from app.utility.colors import C
from app.utility.verify import *
from app.banners.banner import get_random_banner

from lib.core import handler as h

def clear_screen():
    """Clearing the terminal screen"""
    # Win Function
    if os.name == 'nt':
       os.system('cls')
    # Linux Functions
    else:
       os.system('clear')

# --- Menu Functions ---

def main():
    check_critical_files()
    run_verif()
    for i in range(6, 0, -1):
        sys.stdout.write(f"\r{C.SUCCESS}[*] Verification Success! Start Storm: [{i}] {C.RESET}")
        sys.stdout.flush()
        time.sleep(1)

    clear_screen()
    print(get_random_banner())
    ui.stormUI()
    check_update()

    current_module = None
    current_module_name = ""

    options = {
        "IP": "",
        "PORT": "",
        "PASS": "",
        "URL": "",
        "EMAIL": "",
        "HASH": "",
        "MESSAGE": "",
        "USER": "",
        "ID": "",
        "COUNT": "",
        "PATH": "",
        "INTERFACE": "",
        "THREAD": "",
        "DOMAIN": "",
        "HOSTNAME": "",
        "MODULE": ""
    }
    options = ldch.session(options)

    while True:
        START_INV = "\001"
        END_INV = "\002"

        C_INPUT_INV = f"{START_INV}{C.INPUT}{END_INV}"
        C_ERROR_INV = f"{START_INV}{C.ERROR}{END_INV}"
        C_RESET_INV = f"{START_INV}{C.RESET}{END_INV}"

        p_mod = current_module_name if current_module else "~"
        try:
            print(f"{C_INPUT_INV}┌─(storm::framework){C_RESET_INV}-{C_ERROR_INV}[{p_mod}]{C_RESET_INV}")
            promp = f"{C_INPUT_INV}└─➤ {C_RESET_INV}"
            user_input = input(promp).strip().split()
        except KeyboardInterrupt: return
        except EOFError: break

        if not user_input: continue

        cmd = user_input[0].lower()
        args = user_input[1:]

        # Wrap all data into Context
        context = {
            "current_module": current_module,
            "current_module_name": current_module_name,
            "options": options,
            "exit": False
        }

        # HAND IT OVER TO THE FOREMAN (HANDLER)
        new_context = h.execute(cmd, args, context)

        if new_context:
            current_module = new_context["current_module"]
            current_module_name = new_context["current_module_name"]
            options = new_context["options"]

            if new_context.get("exit"): break
        else:
            print(f"[-] Unknown Command: {cmd} > Run the {C.SUCCESS}help{C.RESET} command for more details.")

if __name__ == "__main__":
    main()
